complete refactor

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,64 +1,49 @@
 #!/bin/bash
 
+if [[ "`uname`" == 'Linux' ]] && [[ $UID != 0 ]]; then
+    echo "Please run this script with sudo to be able to install packages"
+    exit 1
+fi
+
+INSTALL_SOURCE=${INSTALL_SOURCE:-"https://raw.githubusercontent.com/g13013/env-bootstrap/master"}
+
 set -e
 
-platform=`uname`
+# load helpers
+[[ -z $(which curl) ]] &&
+  (
+    echo -e "\e[1;32;40mInstalling curl...\033[0m" && apt-get update 1>/dev/null && apt-get install curl -y 1>/dev/null && export PKG_UPDATED=1 ||
+    echo -e "\e[1;31;40mInstalling curl failed\033[0m"
+  )
 
-is_installed() {
-  if [[ -z "$(which $1)" ]]; then
-    return 1
-  fi
+curl -ssL  $INSTALL_SOURCE/install_helpers > /tmp/install_helpers && source /tmp/install_helpers || (echo "Can't load helpers file from $INSTALL_SOURCE/install_helpers" && exit 1)
 
-  return 0
-}
+! is_installed git && (on_mac && xcode-select --install || ensure_installed git) # git is special, on mac we prioritize xcode git version
 
-ensure_installed() {
-  if is_installed $1; then
-    return 0
-  fi
 
-  if is_installed apt-get; then
-    if [[ -z "$APT_UPDATED" ]]; then
-      apt-get update
-      export APT_UPDATED=1
-    fi
-    apt-get install $1 -y
-  elif is_installed brew; then
-    brew update && brew install $1
-  else
-    echo "Can't manually install $1"
-    exit 1
-  fi
-}
-
-# these tools should be already present on mac
 ensure_installed zsh
-ensure_installed git
-ensure_installed curl
 
-curl https://raw.githubusercontent.com/g13013/env-bootstrap/master/install-prezto | zsh
-curl https://raw.githubusercontent.com/g13013/env-bootstrap/master/install-dev-tools | bash
+curl -sSL ${INSTALL_SOURCE}/install-prezto | INSTALL_SOURCE=$INSTALL_SOURCE zsh
+curl -sSL ${INSTALL_SOURCE}/install-dev-tools | INSTALL_SOURCE=$INSTALL_SOURCE bash
 
-tee ~/.zmodules <<EOF
-zstyle ':prezto:load' pmodule \\
-  'fasd' \\
-  'archive' \\
-  'autosuggestions' \\
-  'rsync' \\
-  'tmux' \\
-  'git' \\
-  'environment' \\
-  'terminal' \\
-  'editor' \\
-  'history' \\
-  'directory' \\
-  'spectrum' \\
-  'utility' \\
-  'completion' \\
-  'prompt'
-EOF
+log "Configuring zprezto (zsh)"
+[ ! -f ~/.zmodules ] && (curl -sSL ${INSTALL_SOURCE}/zmodules | tee ~/.zmodules 1>/dev/null) || warn '~/.zmodules already exists, ignoring'
+([ ! -e ~/.zpreztorc ] ||  [ -L ~/.zpreztorc ]) && (curl -sSL ${INSTALL_SOURCE}/zpreztorc | tee ~/.zpreztorc 1>/dev/null) || warn '~/.zpreztorc already exists, ignoring'
 
-echo "[[ -f ~/.zmodules ]] && source ~/.zmodules" | tee -a ~/.zshrc
+if ! is_installed fasd && on_linux; then
+  log "Installing fasd prerequisites"
 
-if [[ "$platform" == "Linux" ]]; then sudo add-apt-repository ppa:aacebedo/fasd; fi
+  if ! is_installed add-apt-repository; then
+    ensure_installed software-properties-common
+    ensure_installed python-software-properties
+  fi
+
+  add-apt-repository ppa:aacebedo/fasd -y 1>/dev/null
+  apt-get update 1>/dev/null
+fi
+
 ensure_installed fasd
+
+warn
+warn "Tweak your list of zprezto modules to load in ~/.zmodules"
+warn
diff --git a/install-dev-tools b/install-dev-tools
--- a/install-dev-tools
+++ b/install-dev-tools
@@ -1,73 +1,61 @@
 #!/bin/bash
 
+INSTALL_SOURCE=${INSTALL_SOURCE:-"https://raw.githubusercontent.com/g13013/env-bootstrap/master"}
+
 set -e
 
-platform=`uname`
+# load helpers
+[[ -z $(which curl) ]] &&  apt-get update && apt-get install curl -y
+curl -ssL  $INSTALL_SOURCE/install_helpers > /tmp/install_helpers && source /tmp/install_helpers || (echo "Can't load helpers file from $INSTALL_SOURCE/install_helpers" && exit 1)
 
-is_installed() {
-  if [[ -z "$(which $1)" ]]; then
-    return 1
-  fi
+! is_installed git && (on_mac && xcode-select --install || ensure_installed git) # git is special, on mac we prioritize xcode git version
 
-  return 0
-}
-
-ensure_installed() {
-  if is_installed $1; then
-    return 0
-  fi
-
-  if is_installed apt-get; then
-    if [[ -z "$APT_UPDATED" ]]; then
-      apt-get update
-      export APT_UPDATED=1
-    fi
-    apt-get install $1 -y
-  elif is_installed brew; then
-    brew update && brew install $1
-  else
-    echo "Can't manually install $1"
-    exit 1
-  fi
-}
-
-ensure_installed git
-ensure_installed curl
-
-if [[ $platform == "Darwin" ]]; then
-  echo
-  echo installing homebrew
-  echo
-  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+if on_mac && ! is_installed brew ; then
+  log "Installing homebrew"
+  /usr/bin/ruby -e "$(curl -sSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+else
+  on_mac && log "homebrew is already installed"
 fi
 
 if ! is_installed nvm; then
   # install nvm, Node version manager
-  echo
-  echo installing nvm
-  echo
-  curl https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh | bash
+  log "Installing nvm"
 
-  tee -a ~/.tools <<EOF
+  curl -SsL https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh | bash
+
+  if in_file 'nvm.sh' ~/.zshrc; then
+    warn "nvm is already loaded from ~/.zshrc, since it will be loaded from ~/.tools it is no longer necessary to keep it there"
+  fi
+
+  if in_file 'nvm.sh' ~/.tools ;then
+    log "nvm is already loaded from ~/.tools"
+  else
+    tee -a ~/.tools 1>/dev/null <<EOF
 # nvm
-export NODE_VERSION=4
 export NVM_DIR="\${HOME}/.nvm"
-# export NVM_DIR="/Users/aboubakr/.nvm"
-[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh" #&& nvm use \$NODE_VERSION # This loads nvm
+[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
 [ -s "\$NVM_DIR/bash_completion" ] && . "\$NVM_DIR/bash_completion"
 
 EOF
+  fi
+else
+  warn "nvm is already installed"
 fi
 
 if ! is_installed rbenv; then
   # install rbenv, Ruby version manager
-  echo
-  echo installing rbenv
-  echo
-  # install rbenv, Ruby version manager
-  curl https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
+  log "Installing rbenv"
 
-  tee -a ~/.tools <<EOF
+  curl -SsL https://raw.githubusercontent.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
+
+  if in_file 'rbenv init' ~/.zshrc; then
+    warn "rbenv is already loaded from ~/.zshrc, since it will be loaded from ~/.tools it is no longer necessary to keep it there"
+  fi
+
+  if in_file 'rbenv init' ~/.tools ;then
+    log "nvm is is already loaded from ~/.tools"
+  else
+    tee -a ~/.tools 1>/dev/null <<EOF
 # rbenv
 export RBENV_ROOT="\${HOME}/.rbenv"
 if [ -d "\${RBENV_ROOT}" ]; then
@@ -76,12 +64,41 @@ if [ -d "\${RBENV_ROOT}" ]; then
 fi
 
 EOF
-
+  fi
+else
+  warn "rbenv is already installed"
 fi
 
-echo "[[ -f ~/.tools ]] && source ~/.tools" | tee -a ~/.zshrc
+if ! in_file ". ~/.tools" ~/.zshrc; then
+  echo "[[ -f ~/.tools ]] && . ~/.tools" | tee -a ~/.zshrc >/dev/null
+fi
 
-source ~/.tools
+if ! in_file ". ~/.tools" ~/.bash_profile; then
+  echo "[[ -f ~/.tools ]] && . ~/.tools" | tee -a ~/.bash_profile >/dev/null
+fi
 
-# install node LTS (4.x)
-nvm install $NODE_VERSION && nvm use $NODE_VERSION
+zsh <<EOF
+# shellcheck source=/dev/null
+source ~/.zshrc;
+source /tmp/install_helpers
+
+log "Installing NodeJs (LTS)"
+nvm install stable
+
+if on_linux; then
+  log "Installing ruby-build prerequisites"
+  ensure_installed bzip2 build-essential libssl-dev libreadline-dev
+fi
+
+latest="\$(rbenv install -l | sed -n '/^[[:space:]]*[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}[[:space:]]*\$/ h;\${g;p;}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//')" &&
+
+if [[ \$(rbenv versions | grep -c "\$latest") -eq 0 ]]; then
+  log "Installing the latest ruby stable version '\$latest'"
+  rbenv install \$latest && rbenv use \$latest --global || log_error "Could not install ruby"
+else
+  log "The latest ruby version '\$latest' is already installed"
+fi
+EOF
+
+
+ensure_installed vim
diff --git a/install-prezto b/install-prezto
--- a/install-prezto
+++ b/install-prezto
@@ -1,48 +1,36 @@
 #!/bin/zsh
 
+INSTALL_SOURCE=${INSTALL_SOURCE:-"https://raw.githubusercontent.com/g13013/env-bootstrap/master"}
+
 set -e
 
-platform=`uname`
+# load helpers
+[[ -z $(which curl) ]] &&  apt-get update && apt-get install curl -y
+curl -ssL  $INSTALL_SOURCE/install_helpers > /tmp/install_helpers && source /tmp/install_helpers || (echo "Can't load helpers file from $INSTALL_SOURCE/install_helpers" && exit 1)
 
-is_installed() {
-  if [[ -z "$(which $1)" ]]; then
-    return 1
-  fi
+! is_installed git && (on_mac && xcode-select --install || ensure_installed git) # git is special, on mac we prioritize xcode git version
 
-  return 0
-}
-
-ensure_installed() {
-  if is_installed $1; then
-    return 0
-  fi
-
-  if is_installed apt-get; then
-    if [[ -z "$APT_UPDATED" ]]; then
-      apt-get update
-      export APT_UPDATED=1
-    fi
-    apt-get install $1 -y
-  elif is_installed brew; then
-    brew update && brew install $1
-  else
-    echo "Can't automatically install $1"
-    exit 1
-  fi
-}
-
-ensure_installed git
-ensure_installed curl
-
-git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
+if [[ ! -e "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
+  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
+else
+  log "zprezto already installed"
+fi
 
 setopt EXTENDED_GLOB
 for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
   if [[ -f "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
-    echo "${ZDOTDIR:-$HOME}/.${rcfile:t} already exists, not copying"
+    warn "${ZDOTDIR:-$HOME}/.${rcfile:t} already exists, not copying"
   else
     ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
   fi
 done
+
+log "Installing zprezto modules"
+warn "    wakatime"
+mkdir -p ~/.zprezto/modules/wakatime &&
+  (curl -sSL https://raw.githubusercontent.com/wbinglee/zsh-wakatime/master/zsh-wakatime.plugin.zsh | tee ~/.zprezto/modules/wakatime/init.zsh) 1>/dev/null
+warn "    zsh-cwd-history"
+mkdir -p ~/.zprezto/modules/zsh-cwd-history &&
+  (curl  -sSL https://raw.githubusercontent.com/ericfreese/zsh-cwd-history/master/zsh-cwd-history.zsh | tee ~/.zprezto/modules/zsh-cwd-history/init.zsh) 1>/dev/null
 
 chsh -s /bin/zsh
